"""Converts a drafted document's plain text into a real .docx file Zahir
can attach to an actual application - most application portals require an
uploaded file, not pasted text (Zahir's explicit request 2026-07-30: "these
need to be attached"). Generated fresh in memory each time a download is
requested, never written to disk, so the underlying drafted text can stay
encrypted at rest in applications.json like everything else in data/
without this needing its own plaintext-on-disk exception.

Styled to match Zahir's own resume conventions (2026-07-31 request: "the
document save function should follow my resume style") - inspected directly
from his real resume file (C:/Users/User/Desktop/GAND/Zahir Resume.docx) via
python-docx rather than guessed: Times New Roman throughout, a compact 10pt
body (headers are distinguished by bold, not by being bigger - an
information-dense style, not a spacious one), and his own teal accent color
on his name. Plain-text structure is inferred with simple heuristics (first
line = name, second = contact info, ALL-CAPS lines = section headers, "- "
lines = bullets, lines matching a date range = bold company/role lines) -
this matches what tailoring/drafting.py's RESUME_SPEC already instructs
Claude to produce, so the heuristics aren't guessing at arbitrary text, they
're reading a format this app itself asked for.
"""

import io
import re

from docx import Document
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.shared import Pt, RGBColor

NAME_ACCENT_COLOR = RGBColor(0x00, 0x78, 0x6C)  # Zahir's own teal, from his real resume's Title run
BODY_FONT = "Times New Roman"
BODY_SIZE = Pt(10.5)
NAME_SIZE = Pt(20)

_DATE_RANGE_RE = re.compile(
    r"\b(19|20)\d{2}\b.{0,15}(-|–|to)\s*(\b(19|20)\d{2}\b|present)", re.IGNORECASE,
)


def _looks_like_header(line: str) -> bool:
    """ALL-CAPS section headers (PROFESSIONAL SUMMARY, EDUCATION, ...) - the
    literal convention tailoring/drafting.py's RESUME_SPEC instructs."""
    return bool(line) and line == line.upper() and any(c.isalpha() for c in line) and len(line) < 60


def _set_base_font(doc: Document) -> None:
    normal = doc.styles["Normal"]
    normal.font.name = BODY_FONT
    normal.font.size = BODY_SIZE


def text_to_docx_bytes(text: str, author: str | None = None) -> bytes:
    doc = Document()
    _set_base_font(doc)

    # python-docx's default Word file properties (Save As dialog, File >
    # Info) list the author as literally "python-docx" - a real, visible
    # tell that the file was generated by a script, and the opposite of an
    # ATS-perfect, looks-hand-made document. Zahir's explicit request
    # 2026-07-31: it should say his own name there instead.
    if author:
        doc.core_properties.author = author
        doc.core_properties.last_modified_by = author

    lines = text.split("\n")
    seen_name = False
    in_contact_block = False
    for raw_line in lines:
        line = raw_line.strip()
        if not line:
            in_contact_block = False
            doc.add_paragraph("")
            continue

        if not seen_name:
            # First non-blank line: the candidate's name, styled like the
            # Title run in Zahir's own resume - bold, larger, his own accent
            # color rather than a generic default.
            p = doc.add_paragraph()
            run = p.add_run(line)
            run.bold = True
            run.font.size = NAME_SIZE
            run.font.color.rgb = NAME_ACCENT_COLOR
            seen_name = True
            in_contact_block = True
            continue

        if in_contact_block and not _looks_like_header(line) and not line.startswith("- "):
            # Contact block right under the name - can be one combined line
            # or several (phone/email/LinkedIn/work authorization each on
            # their own line, seen in real generations), centered either
            # way like the contact line in his resume. Ends at the first
            # blank line, header, or bullet.
            p = doc.add_paragraph(line)
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            continue
        in_contact_block = False

        if line.startswith("- "):
            doc.add_paragraph(line[2:], style="List Bullet")
            continue

        if _looks_like_header(line):
            # Bold, not bigger - his resume distinguishes headers by weight,
            # not size, keeping the document compact and information-dense.
            p = doc.add_paragraph()
            p.add_run(line).bold = True
            continue

        if _DATE_RANGE_RE.search(line) and len(line) < 120:
            # Company/role lines carrying a date range - bold, same as the
            # "SK Life Science, Inc. (SKLSI)  09/2018 - 01/2026" pattern in
            # his real resume.
            p = doc.add_paragraph()
            p.add_run(line).bold = True
            continue

        doc.add_paragraph(line)

    buf = io.BytesIO()
    doc.save(buf)
    return buf.getvalue()
