target_roles:
- name: CIO
  priority_weight: 10
- name: SVP
  priority_weight: 9
- name: VP
  priority_weight: 9
- name: Head of IT
  priority_weight: 9
- name: Director
  priority_weight: 6
industries:
- Lifesciences/Pharma
- Federal Government
search_cadence:
  scheduled_runs_per_day: 3
